# AI add-ons: Tagging and image description (stub for LLM integration)

def generate_tags(image_path: str) -> str:
    # Integrate with LLM or custom model here
    return "tag1, tag2, tag3"

def generate_description(image_path: str) -> str:
    # Integrate with LLM or custom model here
    return "A sample image description generated by LLM." 